// Code generated by protoc-gen-go.
// source: airportdata.proto
// DO NOT EDIT!

/*
Package airportdata is a generated protocol buffer package.

It is generated from these files:
	airportdata.proto

It has these top-level messages:
	Airport
	AirportList
*/
package airportdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Airport struct {
	State            *string  `protobuf:"bytes,1,req,name=state" json:"state,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Code             *string  `protobuf:"bytes,3,req,name=code" json:"code,omitempty"`
	Lat              *float64 `protobuf:"fixed64,4,req,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,5,req,name=lon" json:"lon,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Airport) Reset()                    { *m = Airport{} }
func (m *Airport) String() string            { return proto.CompactTextString(m) }
func (*Airport) ProtoMessage()               {}
func (*Airport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Airport) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Airport) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Airport) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *Airport) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Airport) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

type AirportList struct {
	Airport          []*Airport `protobuf:"bytes,1,rep,name=airport" json:"airport,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *AirportList) Reset()                    { *m = AirportList{} }
func (m *AirportList) String() string            { return proto.CompactTextString(m) }
func (*AirportList) ProtoMessage()               {}
func (*AirportList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AirportList) GetAirport() []*Airport {
	if m != nil {
		return m.Airport
	}
	return nil
}

func init() {
	proto.RegisterType((*Airport)(nil), "airportdata.Airport")
	proto.RegisterType((*AirportList)(nil), "airportdata.AirportList")
}

func init() { proto.RegisterFile("airportdata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8f, 0xbb, 0x0e, 0x82, 0x40,
	0x10, 0x45, 0xc3, 0x2b, 0xc4, 0xa1, 0xc1, 0x09, 0xc5, 0x74, 0x12, 0x2a, 0x2a, 0x0a, 0x7b, 0x0b,
	0x89, 0xa5, 0x85, 0xe1, 0x0f, 0x26, 0x42, 0x41, 0x54, 0x86, 0xc0, 0xfc, 0x7f, 0xcc, 0x3e, 0x34,
	0xdb, 0xdd, 0x73, 0x72, 0x37, 0x7b, 0x07, 0x8e, 0x3c, 0x6f, 0xab, 0x6c, 0x3a, 0xb2, 0x72, 0xb7,
	0x6e, 0xa2, 0x82, 0x45, 0xa0, 0x9a, 0x17, 0xe4, 0x57, 0x87, 0x58, 0x41, 0xb6, 0x2b, 0xeb, 0x44,
	0x51, 0x1d, 0xb7, 0x87, 0xc1, 0x01, 0x22, 0xa4, 0x0b, 0x7f, 0x26, 0x8a, 0xad, 0xb4, 0xd9, 0xb8,
	0xa7, 0x8c, 0x13, 0x25, 0xce, 0x99, 0x8c, 0x25, 0x24, 0x6f, 0x56, 0x4a, 0xeb, 0xb8, 0x8d, 0x06,
	0x13, 0xad, 0x91, 0x85, 0x32, 0x6f, 0x64, 0x69, 0x2e, 0x50, 0xf8, 0xcf, 0xee, 0xf3, 0xae, 0xd8,
	0x41, 0xee, 0xa7, 0x50, 0x54, 0x27, 0x6d, 0x71, 0xae, 0xba, 0x70, 0xad, 0xaf, 0x0e, 0xbf, 0x52,
	0x7f, 0xfa, 0x3f, 0xbf, 0xb1, 0x72, 0x5f, 0x06, 0xf0, 0x30, 0x97, 0x7d, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0xd0, 0x22, 0x89, 0xed, 0x00, 0x00, 0x00,
}
