// Code generated by protoc-gen-go.
// source: placedata.proto
// DO NOT EDIT!

/*
Package placedata is a generated protocol buffer package.

It is generated from these files:
	placedata.proto

It has these top-level messages:
	Place
	PlaceList
*/
package placedata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Place struct {
	State            *string  `protobuf:"bytes,1,req,name=state" json:"state,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Lat              *float64 `protobuf:"fixed64,3,req,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,4,req,name=lon" json:"lon,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Place) Reset()                    { *m = Place{} }
func (m *Place) String() string            { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()               {}
func (*Place) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Place) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Place) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Place) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Place) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

type PlaceList struct {
	Place            []*Place `protobuf:"bytes,1,rep,name=place" json:"place,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlaceList) Reset()                    { *m = PlaceList{} }
func (m *PlaceList) String() string            { return proto.CompactTextString(m) }
func (*PlaceList) ProtoMessage()               {}
func (*PlaceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PlaceList) GetPlace() []*Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func init() {
	proto.RegisterType((*Place)(nil), "placedata.Place")
	proto.RegisterType((*PlaceList)(nil), "placedata.PlaceList")
}

func init() { proto.RegisterFile("placedata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc8, 0x49, 0x4c,
	0x4e, 0x4d, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x85, 0x72, 0xb1, 0x06, 0x80, 0x38, 0x42, 0x22, 0x5c, 0xac, 0xc5, 0x25, 0x89, 0x25, 0xa9, 0x12,
	0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa,
	0x04, 0x13, 0x58, 0x10, 0xcc, 0x16, 0x12, 0xe0, 0x62, 0xce, 0x49, 0x2c, 0x91, 0x60, 0x56, 0x60,
	0xd2, 0x60, 0x0c, 0x02, 0x31, 0xc1, 0x22, 0xf9, 0x79, 0x12, 0x2c, 0x50, 0x91, 0xfc, 0x3c, 0x25,
	0x63, 0x2e, 0x4e, 0xb0, 0xb1, 0x3e, 0x99, 0xc5, 0x25, 0x42, 0x6a, 0x5c, 0xac, 0x60, 0x0b, 0x25,
	0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x04, 0xf4, 0x10, 0xee, 0x01, 0x2b, 0x0a, 0x82, 0x48, 0x3b,
	0x49, 0x43, 0x35, 0xb9, 0x24, 0x96, 0x24, 0x3a, 0xf1, 0xc1, 0x99, 0x01, 0x20, 0x37, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x85, 0x38, 0xb4, 0xef, 0xc5, 0x00, 0x00, 0x00,
}
